### ISSUE TITLE
Beacon/Cartographer spacer for UHF Hotends

### ISSUE THREAD

**Issue by brzn** [Vitalii3D-xyz/VoronLightweightXCarriage#5]
Is there a Beacon/Cartographer spacer for the UHF Hotends?

**Comment by Vitalii3D-xyz** [comment]
Hello @brzn! Thanks for request, I have just added 16mm spacers to the repo. They should be good for most UHF hotends.
![IMG_1950](https://github.com/user-attachments/assets/c529f649-813c-44ee-a936-31cd99facd70)
